version: '3'

services:
  node:
    container_name: crane_be_node
    build:
      context: ../../
      dockerfile: ${PWD}/.docker/compose/Dockerfile.node
    tty: true
    environment:
      - HOST=0.0.0.0
    working_dir: /work
    restart: unless-stopped