export const EMAIL_SUBJECT = {
  VERIFY_EMAIL: 'Verify Your Email Address',
  RESET_PASSWORD: 'Reset your password',
  PASSWORD_UPDATED: 'Your password is now updated',
  REMINDER: 'Reminder: Confirm your email to use Docmap',
  ADMIN_APPROVAL: 'Your practitioner profile has been approved',
  ADMIN_REJECT: 'Your practitioner profile has been returned',
  ADMIN_DELETE_PROFILE: 'Profile has been successfully deleted',
  NEW_APPOINTMENT_SCHEDULED: 'New appointment scheduled',
  APPOINTMENT_UPDATED: 'Appointment updated',
  APPOINTMENT_CANCELLED: 'Appointment has been cancelled',
  ACCOUNT_LINKED: 'Account Connection Confirmation - DocMap',
  OTP_FOR_SECURE_LOGIN: 'Your One-Time Password (OTP) for secure login',
  UPCOMING_APPOINTMENT_REMINDER: 'Upcoming Appointment in 1 Hour',
  NEW_BILLS_TO_REVIEW: '[DocMap] Unpaid billing requires your attention',
  ISSUED_INVOICES: '[DocMap] Successful payment for [billing period] bill',
  OVERDUE_PAYMENTS: '[DocMap] Overdue payment for [billing period] bill',
  UNREAD_MESSAGE: 'You have unread messages waiting',
  SYSTEM_MAINTENANCE_ALERTS: 'Scheduled System Maintenance',
};
